# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 15:29
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroEjecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('origenMuestreo', models.TextField(max_length=10)),
                ('detalleMuestreo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sensorHumedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorHumedadSuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorLuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lux', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorPresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorTemperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorViento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmPorHora', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
    ]
