# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEMA', '0002_estadosensores'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensorco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorpm10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm10', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='sensorpm25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField()),
                ('idMuestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEMA.registroEjecucion')),
            ],
        ),
    ]
