# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEMA', '0004_sensoro3'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosensores',
            name='estadoSensorCo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadosensores',
            name='estadoSensorO3',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadosensores',
            name='estadoSensorPm10',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadosensores',
            name='estadoSensorPm25',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
